USE srb_core;
INSERT INTO condition_def
(cond_key,tf,slot,label_ko,role,param_schema,data_ready,reconstructible,note) VALUES
('IGNITE_10_15','D','A','전일비 +10~15% 점화','FILTER',
 '{"lo":0.10,"hi":0.15}',1,1,'앵커 정의(동결)'),
('AMT20_MIN','D','A','20일 평균거래대금 하한','FILTER',
 '{"min_krw":5000000000}',1,1,NULL),
('AMT_RANK_TODAY','D','E','당일 거래대금 순위','FILTER',
 '{"top_n":3,"pool":"MARKET"}',1,1,'4구간 단조성으로 검증'),
('MKTCAP_BAND','D','A','시가총액 구간','FILTER',
 '{"lo":100000000000,"hi":3000000000000}',0,1,'상장주식수 애드온 선행'),
('MA60_XUP','D','A','60이평 상향돌파 후 N봉 내','FILTER',
 '{"within":3}',1,1,NULL),
('DISP60','D','A','60이평 이격도 범위','FILTER',
 '{"lo":100,"hi":106}',1,1,NULL),
('BB_UPPER_BREAK','D','A','BB 상단 돌파','FILTER',
 '{"len":20,"mult":2.0,"buf_atr":0.0}',1,1,NULL),
('SQZ_PRE','D','A','직전 밴드폭 하위분위','FILTER',
 '{"pct":25,"look":120}',1,1,NULL),
('HH20_BREAK','D','A','20일 신고가 돌파','FILTER',
 '{"len":20}',1,1,'BB와 Jaccard 비교용'),
('POS20','D','A','20일 레인지 내 위치','FILTER',
 '{"lo":0.55,"hi":0.97}',1,1,NULL),
('NOT_BLOWOFF','D','A','급등 과열 제외','FILTER',
 '{"max_ret":0.22}',1,1,NULL),
('PRICE_BAND','D','A','주가 범위','FILTER',
 '{"lo":2000,"hi":200000}',1,1,NULL),
('DEDUP_DAYS','D','X','동일종목 재포착 간격','FILTER',
 '{"days":5}',1,1,'군집 중복 억제'),
('EXCL_HALT','D','A','거래정지 복원 배제','EXCLUSION',
 '{"gap_days":5}',1,1,'인덱스 거래일 대비 결측'),
('EXCL_DELISTED','D','A','폐지·이탈 복원 배제','EXCLUSION',
 '{"tail_days":10}',1,1,'last_seen_date 기반'),
('EXCL_ALERT_RULE','D','A','투자경고 룰 복원 배제','EXCLUSION',
 '{"rule_ver":"TBD"}',0,1,'KRX 규정 확인 필요'),
('EXCL_CAUTION','D','A','투자주의 배제','EXCLUSION',
 '{}',0,0,'복원 불가 → 백로그'),
('MFE_QUALITY','D','A','MFE 품질 채점(컷 없음)','QUALITY',
 '{"win":20,"thr":0.08}',1,1,'건수 미감소, 통과율만 표시');
